{% set name = "ckzg" %}
{% set version = "2.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ckzg-{{ version }}.tar.gz
  sha256: e48e092f9b89ebb6aaa195de2e2bb72ad2d4b35c87d3a15e4545f13c51fbbe30
  patches:
    - setup.py.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  ignore_run_exports:
    - python

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libblst
    - libblst-headers
    - setuptools
  run:
    - python
    - libblst

test:
  imports:
    - ckzg
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/ethereum/c-kzg-4844
  summary: Python bindings for C-KZG-4844
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - step21
    - MementoRC
