{% set name = "ckzg" %}
{% set version = "2.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ckzg-{{ version }}.tar.gz
  sha256: 643eb63f091d8c0cace5618348bb2ca3de96a1e53905b1a7fc608c754e70e29d
  patches:
    - setup.py.patch

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  ignore_run_exports:
    - python

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - libblst
    - libblst-headers
    - setuptools
  run:
    - python
    - libblst

test:
  imports:
    - ckzg
  commands:
    - pip check
  requires:
    - pip
    - python

about:
  home: https://github.com/ethereum/c-kzg-4844
  summary: Python bindings for C-KZG-4844
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - step21
    - MementoRC
